### ISSUE TITLE
Plug-in not working:  Port issue?

### ISSUE THREAD

**Issue by jfischetti22** [SeydX/homebridge-sonybravia-platform#13]
I installed the Bravia plugin, and configured the config file.  I started off slowly only activating the Power and Volume, but neither are working.   I changed the port to be 194 and even set up port forwarding on my router to point to the TV ip address.  Any thoughts why it's not working?

{
				 "platform": "BraviaTV",
				 "name": "TV",
				 "ipadress": "192.168.7.98",
				 "port": 194,
				 "psk": "XXXX",
				 "tvEnabled": true,
				 "volumeEnabled": false,
				 "inputsEnabled": false,
				 "detectCEC": false,
				 "extraInputs": false,
				 "appsEnabled": false,
				 "channelsEnabled": false,
				 "remoteControl": false
			 }

**Comment by seydx** [comment]
Hello,

Can you post the output from following command pls:

curl -s -X POST -d "{\"id\":3,\"method\":\"getPowerStatus\",\"version\":\"1.0\",\"params\":["1.0"]}" "http://IPADRESSHERE/sony/system" -H "X-Auth-PSK: PSKHERE" -v

Please replace IPADRESSHERE and PSKHERE with own data

**Comment by jfischetti22** [comment]
Hello,

I assume I had to paste that command into terminal while connected to raspberrypi:~ $

When I did I only received the following:

[>


It just held at that prompt/





 ___________________________________
J O H N    F I S C H E T T I           
917-723-7420

**Comment by seydx** [comment]
Do you have replace the IPADRESSHERE and PSKHERE?

ipadress i.e. 192.168.1.1 (without Port)
PSK is the password you set in the tv settings before

**Comment by seydx** [comment]
If the above Command dont work, try this One

curl 192.168.178.1 -v

(Replace with the ip Adresse from your tv)

**Comment by jfischetti22** [comment]
That command got a response…

* Rebuilt URL to: 192.168.7.98/
*   Trying 192.168.7.98...
* TCP_NODELAY set
* connect to 192.168.7.98 port 80 failed: No route to host
* Failed to connect to 192.168.7.98 port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to 192.168.7.98 port 80: No route to host

I specifically listed port 194 in the config file for the Bravia plugin, but it looks like it’s still looking for port 80.
I have a security camera system utilizing port 80, so I assume that’s why its not finding the TV.

Any better way to force a different port?

 




 ___________________________________
J O H N    F I S C H E T T I           
917-723-7420

**Comment by jfischetti22** [comment]
Looking at the Homebridge Log file, i see the following, so it is looking for port 194…

May 14 15:09:27 raspberrypi homebridge[10792]: [2018-5-14 15:09:27] [TV] { Error: connect EHOSTUNREACH 192.168.7.98:194
May 14 15:09:27 raspberrypi homebridge[10792]:     at Object._errnoException (util.js:1022:11)
May 14 15:09:27 raspberrypi homebridge[10792]:     at _exceptionWithHostPort (util.js:1044:20)
May 14 15:09:27 raspberrypi homebridge[10792]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
May 14 15:09:27 raspberrypi homebridge[10792]:   code: 'EHOSTUNREACH',
May 14 15:09:27 raspberrypi homebridge[10792]:   errno: 'EHOSTUNREACH',
May 14 15:09:27 raspberrypi homebridge[10792]:   syscall: 'connect',
May 14 15:09:27 raspberrypi homebridge[10792]:   address: '192.168.7.98',
May 14 15:09:27 raspberrypi homebridge[10792]:   port: 194 }

I have port forwarding on my router pointing Port 194 to the TV IP….





 ___________________________________
J O H N    F I S C H E T T I           
917-723-7420
